#!/bin/bash
set -e
cd "$(dirname "$0")"

if [[ "$(uname)" == "Linux" ]]; then
    # Check if Debian-based distro
    if [[ -f "/etc/debian_version" ]]; then
        # Install required packages
        declare -a packages=(
            "python3"
            "python3-pip"
            # "sxhkd"
            # "wmctrl"
        )
        for package in "${packages[@]}"; do
            dpkg -s "$package" >/dev/null 2>&1 || {
                sudo apt-get update
                sudo apt-get install -y "$package"
            }
        done

        # Start sxhkd
        # touch ~/.sxhkdrc
        # killall sxhkd >/dev/null 2>&1 || true
        # setsid sxhkd -c ~/.sxhkdrc >/dev/null 2>&1 &

        # Disable capslock key
        # setxkbmap -option ctrl:nocaps

    # Check if Arch-based distro
    elif [[ -f "/etc/arch-release" ]]; then
        function check_and_install {
            if ! pacman -Qi $1 >/dev/null; then
                echo "Package $1 is not installed."
                echo "Installing $1..."
                sudo pacman -S --noconfirm $1
            fi
        }

        check_and_install 'python'
        check_and_install 'python-pip'
    fi

elif command -v termux-setup-storage; then # is running in termux
    if [[ ! -x "$(command -v python)" ]]; then
        pkg update
        pkg install -y python
    fi
fi

# Bash alias
line="export PATH=\"$(pwd)/bin:\$PATH\""
BASHRC="$HOME/.bashrc"
# Append a line to $BASHRC file if it doesn't already exist.
if [ ! -f "$BASHRC" ] || ! grep -qF -- "$line" "$BASHRC"; then
    echo "$line" >>"$BASHRC"
fi

# Set terminal title
echo -ne '\033]0;MyTerminal\007'

# Default settings for FZF
export FZF_DEFAULT_OPTS='--layout=reverse'

[[ ! -d "$HOME/.venv/myscripts" ]] && python3 -m venv "$HOME/.venv/myscripts" --system-site-packages
source "$HOME/.venv/myscripts/bin/activate"

pip install -r requirements.txt >/dev/null
python myscripts.py "$@"
