#!/bin/bash
set -e
cd "$(dirname "$0")"

# Check if Debian-based Linux distro
if [[ "$(uname)" == "Linux" ]] && [[ -f "/etc/debian_version" ]]; then
    # Install required packages
    declare -a packages=(
        "python3-pip"
        "suckless-tools" # for dmenu
        "sxhkd"
        "wmctrl"
    )
    for package in "${packages[@]}"; do
        dpkg -s "$package" >/dev/null 2>&1 || {
            sudo apt-get update
            sudo apt-get install -y "$package"
        }
    done

    # Start sxhkd
    touch ~/.sxhkdrc
    killall sxhkd >/dev/null 2>&1 || true
    setsid sxhkd -c ~/.sxhkdrc >/dev/null 2>&1 &

    # Disable capslock key
    setxkbmap -option ctrl:nocaps

    # Enable touchpad tapping
    touchpad="$(xinput list --name-only | grep -i touch)"
    echo "Setup touchpad device: $touchpad"
    xinput set-prop "$touchpad" "libinput Tapping Enabled" 1
    xinput set-prop "$touchpad" "libinput Natural Scrolling Enabled" 1

elif command -v termux-setup-storage; then # is running in termux
    source scripts/r/android/termux/setup_termux.sh
fi

pip3 install -r requirements.txt

# Autostart on any Linux desktop
mkdir -p ~/.config/autostart/
cat >~/.config/autostart/myscripts.desktop <<EOF
[Desktop Entry]
Type=Application
Name=MyScripts
Exec=x-terminal-emulator -e $HOME/MyScripts/myscripts --startup
StartupNotify=false
Terminal=false
EOF

# Bash alias
LINE="export PATH=\"$(pwd)/bin:\$PATH\""
BASHRC="$HOME/.bashrc"
# Append a line to $BASHRC file if it doesn't already exist.
if [ ! -f "$BASHRC" ] || ! grep -qF -- "$LINE" "$BASHRC"; then
    echo "$LINE" >>"$BASHRC"
fi

# Set terminal title
echo -ne '\033]0;MyScriptsTerminal\007'

python3 myscripts.py "$@"
