#!/bin/bash
set -e
cd "$(dirname "$0")"

# Check if Debian-based Linux distro
if [[ -f "/etc/debian_version" ]] && [[ "$(uname)" == "Linux" ]]; then
    # Install required packages
    declare -a packages=("python3-pip" "sxhkd" "kitty" "xdotool")
    for package in "${packages[@]}"; do
        dpkg -s "$package" >/dev/null 2>&1 || {
            sudo apt-get update
            sudo apt-get install -y "$package"
        }
    done

    # Start sxhkd
    touch ~/.sxhkdrc
    killall sxhkd >/dev/null 2>&1 || true
    setsid sxhkd -c ~/.sxhkdrc >/dev/null 2>&1 &

    # Disable capslock key
    setxkbmap -option ctrl:nocaps

    # Enable touchpad tapping
    touchpad="$(xinput list --name-only | grep -i touch)"
    xinput set-prop "$touchpad" "libinput Tapping Enabled" 1

elif command -v termux-setup-storage; then # is running in termux
    # Install required packages
    declare -a packages=("python" "git" "gh" "termux-api")
    for package in "${packages[@]}"; do
        dpkg -s "$package" >/dev/null 2>&1 || {
            pkg update
            pkg install -y "$package"
        }
    done

    # Workaround for major performance degradation with most termux-api calls
    # See https://github.com/termux/termux-api/issues/552
    sed -i 's#^exec /system/bin/app_process /#exec /system/bin/app_process -Xnoimage-dex2oat /#' "$PREFIX/bin/am"
fi

pip3 install -r requirements.txt

# Autostart on any Linux desktop
mkdir -p ~/.config/autostart/
cat >~/.config/autostart/myscripts.desktop <<EOF
[Desktop Entry]
Type=Application
Name=MyScripts
Exec=x-terminal-emulator -e $HOME/MyScripts/myscripts --startup
StartupNotify=false
Terminal=false
EOF

# Bash alias
LINE="export PATH=\"$(pwd)/bin:\$PATH\""
BASHRC="$HOME/.bashrc"
# Append a line to $BASHRC file if it doesn't already exist.
if [ ! -f "$BASHRC" ] || ! grep -qF -- "$LINE" "$BASHRC"; then
    echo "$LINE" >>"$BASHRC"
fi

# Set terminal title
echo -ne '\033]0;MyScriptsTerminal\007'

python3 myscripts.py "$@"
