#!/bin/bash
set -e
cd "$(dirname "$0")"

# If Debian-based distro
if [ -f "/etc/debian_version" ]; then
    if [ "$(uname)" == "Linux" ]; then
        if ! type pip3 >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt install python3-pip -y
        fi

        if ! [ -x "$(command -v sxhkd)" ]; then
            sudo apt-get update
            sudo apt-get install sxhkd -y
        fi

        if ! [ -x "$(command -v kitty)" ]; then
            sudo apt-get update
            sudo apt-get install kitty -y
        fi

        if ! [ -x "$(command -v xdotool)" ]; then
            sudo apt-get update
            sudo apt-get install xdotool -y
        fi

        touch ~/.sxhkdrc
        killall sxhkd >/dev/null 2>&1 || true
        setsid sxhkd -c ~/.sxhkdrc >/dev/null 2>&1 &
    fi
fi

pip3 install -r requirement.txt

# Autostart on any Linux desktop
mkdir -p ~/.config/autostart/
cat >~/.config/autostart/myscripts.desktop <<EOF
[Desktop Entry]
Type=Application
Name=MyScripts
Exec=x-terminal-emulator -e $HOME/MyScripts/run --startup
StartupNotify=false
Terminal=false
EOF

# Set terminal title
echo -ne '\033]0;MyScriptsTerminal\007'

python3 run.py "$@"
