#!/bin/bash
set -e
cd "$(dirname "$0")"

# If Debian-based distro
if [ -f "/etc/debian_version" ]; then
    if [ "$(uname)" == "Linux" ]; then
        if ! type pip3 >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt install python3-pip -y
        fi

        if ! [ -x "$(command -v sxhkd)" ]; then
            sudo apt-get update
            sudo apt-get install sxhkd -y
        fi

        if ! [ -x "$(command -v kitty)" ]; then
            sudo apt-get update
            sudo apt-get install kitty -y
        fi

        if ! [ -x "$(command -v xdotool)" ]; then
            sudo apt-get update
            sudo apt-get install xdotool -y
        fi

        touch ~/.sxhkdrc
        killall sxhkd >/dev/null 2>&1 || true
        setsid sxhkd -c ~/.sxhkdrc >/dev/null 2>&1 &
    fi
fi

pip3 install -r requirement.txt
python3 main_console.py "$@"
