plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ross.keylab'
    compileSdk 34

    defaultConfig {
        applicationId "com.ross.keylab"
        // getInputMethod() / AccessibilityService.InputMethod requires API 33.
        minSdk 33
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.12.0'
}
