[colors.bright]
black = "#6272a4"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.normal]
black = "#21222c"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.search.focused_match]
background = "#ff9632"
foreground = "#000000"

[colors.search.matches]
background = "#ffff00"
foreground = "#000000"

[window.dimensions]
columns = 120
lines = 40

[window]
padding.x = 8
padding.y = 8

[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },

  # Disable F1–F12 keys
  { key = "F1",  action = "None" },
  { key = "F2",  action = "None" },
  { key = "F3",  action = "None" },
  { key = "F4",  action = "None" },
  { key = "F5",  action = "None" },
  { key = "F6",  action = "None" },
  { key = "F7",  action = "None" },
  { key = "F8",  action = "None" },
  { key = "F9",  action = "None" },
  { key = "F10", action = "None" },
  { key = "F11", action = "None" },
  { key = "F12", action = "None" },
]
