allow-external-apps=true
volume-keys=volume
terminal-margin-horizontal=0
terminal-margin-vertical=0
terminal-toolbar-height=1.25
extra-keys = [ \
  ['ESC', '/', '-', 'HOME', 'UP', 'END', 'PGUP', {macro: "CTRL b", display: "C-b", popup: {macro: "CTRL b w", display: "C-b w"}}], \
  ['TAB', 'CTRL', 'ALT', 'LEFT', 'DOWN', 'RIGHT', 'PGDN', {macro: "CTRL a", display: "C-a", popup: {macro: "CTRL a w", display: "C-a w"}}] \
]
