allow-external-apps = true
volume-keys = volume
terminal-margin-horizontal = 0
terminal-margin-vertical = 0
extra-keys = [ \
  [{macro: "CTRL a", display: "C-a"}, 'ESC', '/', '-', 'HOME', {key: 'UP', popup: {macro: "CTRL a w", display: "C-a w"}}, 'END', 'PGUP'], \
  [{macro: "CTRL b", display: "C-b"}, 'TAB', 'CTRL', 'ALT', 'LEFT', {key: 'DOWN', popup: {macro: "CTRL a w", display: "C-a w"}}, 'RIGHT', 'PGDN'] \
]
