allow-external-apps = true
volume-keys = volume
terminal-margin-horizontal = 0
terminal-margin-vertical = 0
extra-keys = [ \
  [{macro: "CTRL a", display: "C-a"}, 'ESC', '/', '-', 'HOME', 'UP', 'END', 'PGUP'], \
  [{macro: "CTRL q", display: "C-q"}, 'TAB', 'CTRL', 'ALT', 'LEFT', 'DOWN', 'RIGHT', 'PGDN'] \
]
