import sys
import os
import subprocess
import traceback
import _appmanager
from _shutil import run_elevated

assoc = {
    ".3g2": ["mpv", "VLC"],
    ".3gp": ["mpv", "VLC"],
    ".3gp2": ["mpv", "VLC"],
    ".3gpp": ["mpv", "VLC"],
    ".4-win-x64": ["PathAdd"],
    ".aac": ["mpv", "VLC"],
    ".abnf": ["notepad++", "vscode"],
    ".ac3": ["mpv", "VLC"],
    ".aco": ["notepad++", "vscode"],
    ".ahk": ["notepad++", "vscode"],
    ".ai": ["AI"],
    ".aliases": ["notepad++", "vscode"],
    ".amr": ["mpv", "VLC"],
    ".amv": ["mpv", "VLC"],
    ".ape": ["mpv", "VLC"],
    ".ase": ["notepad++", "vscode"],
    ".asf": ["mpv", "VLC"],
    ".asp": ["notepad++", "vscode"],
    ".ass": ["mpv", "VLC"],
    ".asset": ["notepad++", "vscode"],
    ".asx": ["mpv", "VLC"],
    ".au3": ["notepad++", "vscode"],
    ".avi": ["mpv", "VLC"],
    ".bak": ["notepad++", "vscode"],
    ".bash_profile": ["notepad++", "vscode"],
    ".bashrc": ["notepad++", "vscode"],
    ".bat": ["notepad++", "vscode"],
    ".bib": ["notepad++", "vscode"],
    ".bin": ["HxD"],
    ".bind": ["notepad++", "vscode"],
    ".bmp": ["IrfanView"],
    ".bnf": ["notepad++", "vscode"],
    ".c": ["notepad++", "vscode"],
    ".c_": ["notepad++", "vscode"],
    ".cbp": ["notepad++", "vscode"],
    ".cfg": ["notepad++", "vscode"],
    ".cl7": ["notepad++", "vscode"],
    ".classpath": ["notepad++", "vscode"],
    ".cls": ["notepad++", "vscode"],
    ".cmake": ["notepad++", "vscode"],
    ".cmd": ["notepad++", "vscode"],
    ".cmdline": ["notepad++", "vscode"],
    ".cnf": ["notepad++", "vscode"],
    ".conf": ["notepad++", "vscode"],
    ".conffiles": ["notepad++", "vscode"],
    ".config": ["notepad++", "vscode"],
    ".conv": ["notepad++", "vscode"],
    ".cpp": ["notepad++", "vscode"],
    ".cps": ["notepad++", "vscode"],
    ".crash": ["notepad++", "vscode"],
    ".crdownload": ["mpv", "VLC"],
    ".crt": ["notepad++", "vscode"],
    ".cs": ["notepad++", "vscode"],
    ".cson": ["notepad++", "vscode"],
    ".css": ["notepad++", "vscode"],
    ".csv": ["notepad++", "tad"],
    ".cu": ["notepad++", "vscode"],
    ".cue": ["mpv", "VLC"],
    ".cxx": ["notepad++", "vscode"],
    ".dat": ["mpv", "VLC"],
    ".dbml": ["notepad++", "vscode"],
    ".def": ["notepad++", "vscode"],
    ".desktop": ["notepad++", "vscode"],
    ".divx": ["mpv", "VLC"],
    ".dll": ["PathAdd"],
    ".dmskm": ["mpv", "VLC"],
    ".dng": ["IrfanView"],
    ".docx": ["LibreOfficeWriter"],
    ".downloading": ["mpv", "VLC"],
    ".dpg": ["mpv", "VLC"],
    ".dpl": ["mpv", "VLC"],
    ".driveignore": ["notepad++", "vscode"],
    ".dropbox": ["notepad++", "vscode"],
    ".dtapart": ["mpv", "VLC"],
    ".dts": ["mpv", "VLC"],
    ".dtshd": ["mpv", "VLC"],
    ".dvr-ms": ["mpv", "VLC"],
    ".dxf": ["notepad++", "vscode"],
    ".dot": ["notepad++", "vscode"],
    ".eac3": ["mpv", "VLC"],
    ".efu": ["notepad++", "vscode"],
    ".ejs": ["notepad++", "vscode"],
    ".el": ["notepad++", "vscode"],
    ".emacs": ["notepad++", "vscode"],
    ".emf": ["notepad++", "vscode"],
    ".eml": ["notepad++", "vscode"],
    ".env": ["notepad++", "vscode"],
    ".eps": ["notepad++", "vscode"],
    ".epub": ["SumatraPDF", "adobereader"],
    ".erb": ["notepad++", "vscode"],
    ".evo": ["mpv", "VLC"],
    ".exe": ["PathAdd"],
    ".f4v": ["mpv", "VLC"],
    ".ffs_batch": ["notepad++", "vscode"],
    ".ffs_gui": ["notepad++", "vscode"],
    ".flac": ["mpv", "VLC"],
    ".flv": ["mpv", "VLC"],
    ".frag": ["notepad++", "vscode"],
    ".gif": ["IrfanView"],
    ".git-credentials": ["notepad++", "vscode"],
    ".gitconfig": ["notepad++", "vscode"],
    ".gitignore": ["notepad++", "vscode"],
    ".gradle": ["notepad++", "vscode"],
    ".grid": ["notepad++", "vscode"],
    ".h": ["notepad++", "vscode"],
    ".h_": ["notepad++", "vscode"],
    ".hpp": ["notepad++", "vscode"],
    ".htk": ["notepad++", "vscode"],
    ".htm": ["notepad++", "vscode"],
    ".html": ["notepad++", "vscode"],
    ".hxx": ["notepad++", "vscode"],
    ".i": ["notepad++", "vscode"],
    ".ico": ["IrfanView"],
    ".idc": ["notepad++", "vscode"],
    ".idx": ["mpv", "VLC"],
    ".ifo": ["mpv", "VLC"],
    ".iim": ["notepad++", "vscode"],
    ".iml": ["notepad++", "vscode"],
    ".index": ["notepad++", "vscode"],
    ".inf": ["notepad++", "vscode"],
    ".info": ["notepad++", "vscode"],
    ".ini": ["notepad++", "vscode"],
    ".inl": ["notepad++", "vscode"],
    ".ino": ["notepad++", "vscode"],
    ".ipynb": ["notepad++", "vscode"],
    ".iso": ["mpv", "VLC"],
    ".iss": ["notepad++", "vscode"],
    ".itf": ["notepad++", "vscode"],
    ".jade": ["notepad++", "vscode"],
    ".java": ["notepad++", "vscode"],
    ".jpeg": ["IrfanView"],
    ".jpg": ["IrfanView"],
    ".js": ["notepad++", "vscode"],
    ".json": ["notepad++", "vscode"],
    ".jsonlz4": ["notepad++", "vscode"],
    ".jsx": ["notepad++", "vscode"],
    ".k3g": ["mpv", "VLC"],
    ".keystore": ["notepad++", "vscode"],
    ".launch": ["notepad++", "vscode"],
    ".less": ["notepad++", "vscode"],
    ".list": ["notepad++", "vscode"],
    ".lmp4": ["mpv", "VLC"],
    ".lnk": ["HxD"],
    ".log": ["notepad++", "vscode"],
    ".lrc": ["notepad++", "vscode"],
    ".lyx": ["notepad++", "vscode"],
    ".lua": ["notepad++", "vscode"],
    ".m1a": ["mpv", "VLC"],
    ".m1v": ["mpv", "VLC"],
    ".m2a": ["mpv", "VLC"],
    ".m2t": ["mpv", "VLC"],
    ".m2ts": ["mpv", "VLC"],
    ".m2v": ["mpv", "VLC"],
    ".m3u": ["mpv", "VLC"],
    ".m3u8": ["mpv", "VLC"],
    ".m4a": ["mpv", "VLC"],
    ".m4b": ["mpv", "VLC"],
    ".m4p": ["mpv", "VLC"],
    ".m4v": ["mpv", "VLC"],
    ".manifest": ["notepad++", "vscode"],
    ".markdown": ["notepad++", "vscode"],
    ".mat": ["notepad++", "vscode"],
    ".md": ["notepad++", "vscode"],
    ".mdt": ["notepad++", "vscode"],
    ".meta": ["notepad++", "vscode"],
    ".mf": ["notepad++", "vscode"],
    ".mk": ["notepad++", "vscode"],
    ".mka": ["mpv", "VLC"],
    ".mkd": ["notepad++", "vscode"],
    ".mkv": ["mpv", "VLC"],
    ".mod": ["mpv", "VLC"],
    ".modules": ["notepad++", "vscode"],
    ".mov": ["mpv", "VLC"],
    ".mp2": ["mpv", "VLC"],
    ".mp2v": ["mpv", "VLC"],
    ".mp3": ["mpv", "Audacity"],
    ".mp4": ["mpv", "VLC"],
    ".mpa": ["mpv", "VLC"],
    ".mpc": ["mpv", "VLC"],
    ".mpe": ["mpv", "VLC"],
    ".mpeg": ["mpv", "VLC"],
    ".mpg": ["mpv", "VLC"],
    ".mpl": ["mpv", "VLC"],
    ".mpls": ["mpv", "VLC"],
    ".mpv2": ["mpv", "VLC"],
    ".mqv": ["mpv", "VLC"],
    ".ms11": ["notepad++", "vscode"],
    ".mtl": ["notepad++", "vscode"],
    ".mts": ["mpv", "VLC"],
    ".npy": ["notepad++", "vscode"],
    ".nsh": ["notepad++", "vscode"],
    ".nsi": ["notepad++", "vscode"],
    ".nsr": ["mpv", "VLC"],
    ".nsv": ["mpv", "VLC"],
    ".obj": ["notepad++", "vscode"],
    ".ods": ["LibreOfficeWriter"],
    ".odt": ["LibreOfficeWriter"],
    ".ogg": ["mpv", "VLC"],
    ".ogm": ["mpv", "VLC"],
    ".ogv": ["mpv", "VLC"],
    ".org": ["notepad++", "vscode"],
    ".out": ["notepad++", "vscode"],
    ".p12": ["notepad++", "vscode"],
    ".pac": ["notepad++", "vscode"],
    ".pak": ["notepad++", "vscode"],
    ".part": ["mpv", "VLC"],
    ".pbtxt": ["notepad++", "vscode"],
    ".pcap": ["notepad++", "vscode"],
    ".pde": ["notepad++", "vscode"],
    ".pdf": ["SumatraPDF", "adobereader"],
    ".pem": ["notepad++", "vscode"],
    ".pgc": ["notepad++", "vscode"],
    ".php": ["notepad++", "vscode"],
    ".pkl": ["notepad++", "vscode"],
    ".pl": ["notepad++", "vscode"],
    ".plantuml": ["notepad++", "vscode"],
    ".pls": ["mpv", "VLC"],
    ".png": ["IrfanView"],
    ".ppm": ["IrfanView"],
    ".ppo": ["notepad++", "vscode"],
    ".prefs": ["notepad++", "vscode"],
    ".pri": ["notepad++", "vscode"],
    ".pro": ["notepad++", "vscode"],
    ".project": ["notepad++", "vscode"],
    ".properties": ["notepad++", "vscode"],
    ".props": ["notepad++", "vscode"],
    ".ps1": ["notepad++", "vscode"],
    ".psm1": ["notepad++", "vscode"],
    ".pub": ["notepad++", "vscode"],
    ".pxd": ["notepad++", "vscode"],
    ".py": ["notepad++", "vscode"],
    ".pyd": ["notepad++", "vscode"],
    ".pyx": ["notepad++", "vscode"],
    ".qsv": ["mpv", "VLC"],
    ".qtpotp": ["mpv", "VLC"],
    ".r": ["notepad++", "vscode"],
    ".ram": ["mpv", "VLC"],
    ".rapotp": ["mpv", "VLC"],
    ".rb": ["notepad++", "vscode"],
    ".record": ["notepad++", "vscode"],
    ".reg": ["notepad++", "vscode"],
    ".res": ["notepad++", "vscode"],
    ".rmpotp": ["mpv", "VLC"],
    ".rmvb": ["mpv", "VLC"],
    ".rpm": ["mpv", "VLC"],
    ".script": ["notepad++", "vscode"],
    ".sdirs": ["notepad++", "vscode"],
    ".sgy": ["notepad++", "vscode"],
    ".sh": ["notepad++", "vscode"],
    ".shader": ["notepad++", "vscode"],
    ".skm": ["mpv", "VLC"],
    ".sln": ["notepad++", "vscode"],
    ".smali": ["notepad++", "vscode"],
    ".smi": ["mpv", "VLC"],
    ".sql": ["notepad++", "vscode"],
    ".srt": ["notepad++", "vscode"],
    ".ssa": ["mpv", "VLC"],
    ".sub": ["mpv", "VLC"],
    ".sublime-menu": ["notepad++", "vscode"],
    ".sublime-package": ["notepad++", "vscode"],
    ".sublime-settings": ["notepad++", "vscode"],
    ".svg": ["IrfanView"],
    ".swf": ["mpv", "VLC"],
    ".tak": ["mpv", "VLC"],
    ".td": ["mpv", "VLC"],
    ".tdl": ["mpv", "VLC"],
    ".tex": ["notepad++", "vscode"],
    ".tif": ["IrfanView"],
    ".tiff": ["IrfanView"],
    ".tmlanguage": ["notepad++", "vscode"],
    ".tmpreferences": ["notepad++", "vscode"],
    ".tp": ["notepad++", "vscode"],
    ".tpl": ["notepad++", "vscode"],
    ".tppotp": ["mpv", "VLC"],
    ".tpr": ["mpv", "VLC"],
    ".trp": ["mpv", "VLC"],
    ".ts": ["notepad++", "vscode"],
    ".tspotp": ["mpv", "VLC"],
    ".tsv": ["notepad++", "vscode"],
    ".tud": ["mpv", "VLC"],
    ".txt": ["notepad++", "vscode"],
    ".ui": ["notepad++", "vscode"],
    ".user": ["notepad++", "vscode"],
    ".vbs": ["notepad++", "vscode"],
    ".vcf": ["notepad++", "vscode"],
    ".vcproj": ["notepad++", "vscode"],
    ".vcxproj": ["notepad++", "vscode"],
    ".vec": ["HxD"],
    ".vert": ["notepad++", "vscode"],
    ".vmx": ["notepad++", "vscode"],
    ".vob": ["mpv", "VLC"],
    ".wav": ["mpv", "Audacity"],
    ".wax": ["mpv", "VLC"],
    ".wdapk": ["notepad++", "vscode"],
    ".webm": ["mpv", "VLC"],
    ".wma": ["mpv", "VLC"],
    ".wmf": ["notepad++", "vscode"],
    ".wmp": ["mpv", "VLC"],
    ".wmpotp": ["mpv", "VLC"],
    ".wmv": ["mpv", "VLC"],
    ".wmx": ["mpv", "VLC"],
    ".wtv": ["mpv", "VLC"],
    ".wvpotp": ["mpv", "VLC"],
    ".wvx": ["mpv", "VLC"],
    ".x68": ["notepad++", "vscode"],
    ".xls": ["notepad++", "vscode"],
    ".xml": ["notepad++", "vscode"],
    ".xyz": ["notepad++", "vscode"],
    ".yaml": ["notepad++", "vscode"],
    ".yml": ["notepad++", "vscode"],
    ".zim": ["notepad++", "vscode"],
    ".zip": ["7zFM"],
    ".zxp": ["notepad++", "vscode"],
    ".gz": ["7zFM"],
    ".usf": ["notepad++", "vscode"],
    ".tar": ["7zFM"],
}


def open_with(file, program_id=0):
    ext = os.path.splitext(file)[1].lower()

    # HACK: hijack extension handling
    if ext == ".vhd":
        run_elevated(["powershell", "-Command", "Mount-VHD -Path '%s'" % file])
        return

    if ext not in assoc:
        raise Exception("%s is not defined" % ext)

    program = assoc[ext][program_id]
    args = [_appmanager.get_executable(program), file]
    subprocess.Popen(args, close_fds=True)


if __name__ == "__main__":
    try:
        file = sys.argv[1]
        program_id = int(sys.argv[2]) if len(sys.argv) >= 3 else 0
        open_with(file, program_id)
    except Exception as e:
        traceback.print_exc(file=sys.stdout)
        print(e)
        input()
